-- Invoked by typing "verify_turtle" into the normal CraftOS shell.
assert(shell.getRunningProgram() == "verify_turtle.lua")
assert(turtle.select(1))
assert(turtle.refuel(1))
assert(turtle.getFuelLevel() == 80)
assert(turtle.forward())
assert(turtle.turnRight())
assert(turtle.select(2))
assert(turtle.place())
local found, block = turtle.inspect()
assert(found and block.name == "minecraft:dirt")
local moved, reason = turtle.forward()
assert(not moved and reason == "Movement obstructed")
assert(turtle.turnLeft())
assert(turtle.forward())
assert(turtle.getFuelLevel() == 78)
assert(turtle.getItemCount(1) == 0 and turtle.getItemCount(2) == 1)
local result = assert(fs.open("wasm-turtle-result.txt", "w"))
result.write("shell=ok; movement=ok; placement=ok; inspection=ok; obstruction=ok; fuel=78; inventory=ok")
result.close()
print("WASM_TURTLE_OK")
